[package]
name = "komorebi_custom_offset"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
ctrlc = "3.4.7"
komorebi-client = { git = "https://github.com/LGUG2Z/komorebi" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
