[package]
name = "komorebi_custom_offset"
version = "0.1.1.1"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
komorebi-client = { git = "https://github.com/LGUG2Z/komorebi" }
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1", features = ["full"] }